import polars as pl

AGENTS = pl.Schema(
    {
        "key": pl.String,
        "auto_generate": pl.Boolean,
        "is_caster": pl.Boolean,
        "small_icon": pl.String,
        "associated_unit_override": pl.String,
        "audio_voiceover_actor_group": pl.String,
        "show_in_ui": pl.Boolean,
        "cap": pl.Int64,
        "has_female_name": pl.Boolean,
        "can_gain_xp": pl.Boolean,
        "loyalty_is_applicable": pl.Boolean,
        "contributes_to_agent_cap": pl.Boolean,
        "recruitment_category": pl.String,
        "magic_lore": pl.String,
        "names_group": pl.Null,
        "can_be_loaned": pl.Boolean,
        "recruitable": pl.Boolean,
        "saving_settings": pl.String,
        "audio_vo_culture_override": pl.Null,
        "spam_click_vo_enabled": pl.Boolean,
        "can_equip_ancillaries": pl.Boolean,
        "cost": pl.Int64,
        "recruitment_button_active_icon_path": pl.Null,
        "recruitment_button_background_icon_path": pl.Null,
    },
)
CHARACTERS = pl.Schema(
    {
        "art_set_id": pl.String,
        "agent_type": pl.String,
        "culture": pl.Null,
        "subculture": pl.Null,
        "faction": pl.Null,
        "is_custom": pl.Boolean,
        "is_male": pl.Boolean,
        "agent_subtype": pl.String,
        "campaign_map_scale": pl.Float64,
    },
)
FACTIONS = pl.Schema(
    {
        "banner_colour_tertiary": pl.String,
        "override_target_unit_vo_culture": pl.Boolean,
        "movie_death_event": pl.Int64,
        "alt_secondary_colour_hex": pl.Int64,
        "flags_path": pl.String,
        "faction_swapping_id": pl.String,
        "cdir_military_generator_config": pl.String,
        "neutral_reinforcement_factions": pl.String,
        "uniform_colour_primary": pl.String,
        "ui_main_theme_skin": pl.String,
        "win_movie": pl.Null,
        "is_quest_faction": pl.Boolean,
        "index": pl.Int64,
        "is_rebel": pl.Boolean,
        "waaagh_faction": pl.Null,
        "subculture": pl.String,
        "key": pl.String,
        "category": pl.String,
        "unit_regiment_name_group": pl.String,
        "waaagh_general_unit": pl.String,
        "default_audio_actor_vo_group": pl.String,
        "text_replacement_key": pl.String,
        "music_feedback_group": pl.String,
        "primary_colour_hex": pl.String,
        "alt_primary_colour_hex": pl.Float64,
        "banner_colour_secondary": pl.String,
        "ship_name_group": pl.String,
        "mp_force_gen_template": pl.String,
        "name_group": pl.String,
        "feature_forest": pl.String,
        "can_accept_gifts_when_dead": pl.Boolean,
        "uniform_colour_secondary": pl.String,
        "banner_colour_primary": pl.String,
        "secondary_colour_hex": pl.String,
        "alt_uniform_colour_hex": pl.Int64,
        "uniform_colour_hex": pl.Int64,
        "rebel_colour_hex": pl.Int64,
        "pre_battle_speech_parameter": pl.String,
        "primary_colour": pl.String,
        "skin": pl.String,
        "card_colour_hex": pl.Int64,
        "military_group": pl.String,
        "ui_skin": pl.String,
        "audio_voiceover_culture": pl.String,
        "uniform_colour_tertiary": pl.String,
    },
)
